#!/usr/bin/env bash

# Script Working Directory
swd() {
    local SOURCE_PATH="${BASH_SOURCE[0]}"
    local SYMLINK_DIR
    local SCRIPT_DIR
    # Resolve symlinks recursively
    while [ -L "$SOURCE_PATH" ]; do
        # Get symlink directory
        SYMLINK_DIR="$( cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd )"
        # Resolve symlink target (relative or absolute)
        SOURCE_PATH="$(readlink "$SOURCE_PATH")"
        # Check if candidate path is relative or absolute
        if [[ $SOURCE_PATH != /* ]]; then
            # Candidate path is relative, resolve to full path
            SOURCE_PATH=$SYMLINK_DIR/$SOURCE_PATH
        fi
    done
    # Get final script directory path from fully resolved source path
    SCRIPT_DIR="$(cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd)"
    echo "$SCRIPT_DIR"
}

cwd="$(swd)"    # config working directory
source "${cwd}/util.sh"

# helper function
_help() {
    echo "Usage: "
    echo "  ${0} [OPTION] <install|update>..."
    echo "  With no OPTION or CONFIG specified defaults to -h."
    echo ""
    echo "Options:"
    echo "  -h, --help      Print this help menu"
}

if [[ "$#" -eq 0 ]]; then
    _help
    exit 0
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help)
            _help
            exit 0
            shift
            ;;
        install)
            shift
            "${cwd}/install.sh" "$@"
            exit 0
            ;;
        update)
            shift
            "${cwd}/update.sh" "$@"
            exit 0
            ;;
        *|-*|--*)
            echo "[ERRO] Unknown option $1"
            _help
            exit 1
            shift
            ;;
    esac
done
